# Generated by Django 5.2.5 on 2025-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default=0.0007631874298540965, max_length=150),
            preserve_default=False,
        ),
    ]
