# Generated by Django 5.2.5 on 2025-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='17/11/2025', max_length=200),
        ),
    ]
