# Generated by Django 5.2.5 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0004_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
