# Generated by Django 5.2.5 on 2025-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0005_portfolio_github_portfolio_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
